
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=animalCare
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5435:5432'
  animalcare:
    image: animalcare
    ports:
      - "8086:8081"
    depends_on:
      - postgres
